### ISSUE TITLE
`mesos events` FileDoesNotExist Error

### ISSUE THREAD

**Issue by nicgrayson** [mesosphere/mesos-cli#69]
I've tried installing from pip and from master and get this error on mac os:

```
mesos events                                                                                    ngrayson@nicgrayson
Traceback (most recent call last):
  File "/usr/local/bin/mesos-events", line 9, in <module>
    load_entry_point('mesos.cli==0.1.4', 'console_scripts', 'mesos-events')()
  File "/usr/local/lib/python2.7/site-packages/mesos.cli-0.1.4-py2.7.egg/mesos/cli/cli.py", line 81, in wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/mesos.cli-0.1.4-py2.7.egg/mesos/cli/log.py", line 44, in timer
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/mesos.cli-0.1.4-py2.7.egg/mesos/cli/cli.py", line 55, in wrapper
    return fn(cmd_args, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/mesos.cli-0.1.4-py2.7.egg/mesos/cli/cmds/events.py", line 66, in main
    add_reader(MASTER.log)
  File "/usr/local/lib/python2.7/site-packages/mesos.cli-0.1.4-py2.7.egg/mesos/cli/cmds/events.py", line 57, in add_reader
    log.seek(0, POSITION)
  File "/usr/local/lib/python2.7/site-packages/mesos.cli-0.1.4-py2.7.egg/mesos/cli/mesos_file.py", line 107, in seek
    self._offset = self.size + offset
  File "/usr/local/lib/python2.7/site-packages/mesos.cli-0.1.4-py2.7.egg/mesos/cli/util.py", line 57, in __get__
    value = self.fget(inst)
  File "/usr/local/lib/python2.7/site-packages/mesos.cli-0.1.4-py2.7.egg/mesos/cli/mesos_file.py", line 99, in size
    return self._fetch()["offset"]
  File "/usr/local/lib/python2.7/site-packages/mesos.cli-0.1.4-py2.7.egg/mesos/cli/mesos_file.py", line 81, in _fetch
    raise exceptions.FileDoesNotExist("No such file or directory.")
mesos.cli.exceptions.FileDoesNotExist: No such file or directory.
```

I should note that other commands work just fine for me.

**Comment by ssk2** [comment]
Hi @nicgrayson, this CLI has been deprecated and is being replaced with the DCOS CLI (https://github.com/mesosphere/dcos-cli). We're amidst porting this functionality over.

**Comment by nicgrayson** [comment]
Thanks for this reply.

**Comment by nicgrayson** [comment]
@ssk2 what if I don't use DCOS? Is there still support for non-dcos usage somewhere?

**Comment by ssk2** [comment]
@nicgrayson - sorry for the delay, was out of office. We will support open source Mesos and Marathon with the DCOS CLI so you can use it without DCOS. Some functionality will be unavailable but we're planning on at least having parity with this CLI.
